services:
  - type: web
    name: group-call-server
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn server:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
